# Generated by Django 3.2.6 on 2021-10-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user',
            new_name='admin',
        ),
    ]
